import { v4 as uuidv4 } from 'uuid';

export default {
    personal: {
        firstName: 'John',
        lastName: 'Smith',
        phone: '(415) 555-2938',
        email: 'john.smith@example.com',
        address: 'NYC',
        linkedIn: '',
        website: 'johnsmith.dev',
    },
    education: {
        school: 'University of California, Berkeley',
        degree: 'B.S.',
        major: 'Computer Science',
        minor: 'Tech Management',
        startDate: '2022-09',
        endDate: '2026-06',
        gpa: '3.87',
        coursework: [
            'Data Structures',
            'Algorithm Design and Analysis',
            'Object-Oriented Programming in C++',
            'Computer Systems',
            'Computer Architecture',
            'Database Systems',
            'Statistics Modeling for CS',
            'Technology Marketing',
            'Computer Graphics',
        ],
    },
    experience: [
        {
            id: uuidv4(),
            title: 'Software Engineer',
            company: 'Render Labs',
            location: 'New York, NY',
            startDate: '2025-01',
            endDate: '2025-04',
            bullets: [
                'Developed an automated, usage-based billing system leveraging Circle’s SDK, processing payments and eliminating 5–10 hours/week of manual effort.',
                'Optimized 3D asset backend using Next.js and Supabase, improving task handling and boosting user responsiveness by 50%.',
                'Collaborated in a 12+ member cross-functional team using Agile for system design, API integration, and code reviews.',
            ],
        },
        {
            id: uuidv4(),
            title: 'Software Engineer',
            company: 'Render Labs',
            location: 'San Francisco, CA',
            startDate: '2024-10',
            endDate: '2024-12',
            bullets: [
                'Enabled log monitoring in VS Code using WebSocket communication for real-time debugging.',
                'Built a Retrieval-Augmented Generation chatbot to reduce support load for Render’s 100k+ monthly users.',
                'Implemented frontend (Next.js) and backend (FastAPI) with session management.',
            ],
        },
        {
            id: uuidv4(),
            title: 'Software Engineer Intern',
            company: 'SynthStream Inc.',
            location: 'Tokyo, JP',
            startDate: '2024-06',
            endDate: '2024-08',
            bullets: [
                'Reduced thumbnail generation time by 70% using Sharp.js via Express.js async API.',
                'Built React-DnD timeline editor for video usability.',
                'Used Redis to speed up ElevenLabs API data queries by 50%.',
            ],
        },
        {
            id: uuidv4(),
            title: 'Software Engineer Intern',
            company: 'BlockData LLC',
            location: 'Remote',
            startDate: '2023-06',
            endDate: '2024-09',
            bullets: [
                'Developed Java Spring Boot microservice for real-time crypto market data ingestion via Binance API (8,000+ data pts/sec) → AWS RDS.',
                'Improved stability by resolving 5 critical bugs and achieved 90% unit test coverage using JUnit.',
            ],
        },
    ],
    projects: [
        {
            id: uuidv4(),
            name: 'Parallel Transactional & Analytical Database System',
            tech: 'Python - Database Systems',
            description:
                'Multi-threaded Python DB for OLTP/OLAP with MVCC/2PL-locking.',
        },
        {
            id: uuidv4(),
            name: 'Financial Decision Prediction Model',
            tech: 'Python - AISC',
            description:
                'Built ML model using Pandas/Scikit-learn (98% accuracy) on Kaggle.',
        },
    ],
    skills: {
        languages: [
            'Java',
            'Python',
            'C/C++',
            'JavaScript',
            'TypeScript',
            'HTML/CSS',
            'R',
            'Assembly',
            'PostgreSQL',
            'MATLAB',
        ],
        frameworks: [
            'Spring Boot',
            'Flask',
            'JUnit',
            'Next.js',
            'Material-UI',
            'FastAPI',
        ],
        developerTools: [
            'Git',
            'Docker',
            'Postman',
            'MongoDB',
            'Eclipse',
            'VS Code',
        ],
        libraries: [
            'Pandas',
            'NumPy',
            'Scikit-learn',
            'OpenCV',
            'Matplotlib',
            'Three.js',
            'WebGL',
        ],
    },
};
